# Generated by Django 6.1.1 on 2026-09-26 18:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('EQUITY', 'Equity')], max_length=12)),
                ('is_party_control', models.BooleanField(default=False)),
                ('business', models.CharField(choices=[('chicken_center', 'Sai Charan Chicken Center'), ('feeds', 'Sai Ram Feeds'), ('layer', 'Layer Farm'), ('common', 'Common / Shared')], default='common', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('EDIT', 'Edit'), ('DELETE', 'Delete'), ('REVERSE', 'Reverse')], max_length=10)),
                ('object_type', models.CharField(max_length=60)),
                ('object_id', models.CharField(max_length=40)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('BOTH', 'Customer & Supplier')], default='CUSTOMER', max_length=10)),
                ('business', models.CharField(choices=[('chicken_center', 'Sai Charan Chicken Center'), ('feeds', 'Sai Ram Feeds'), ('layer', 'Layer Farm'), ('common', 'Common / Shared')], default='chicken_center', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='accounting.account')),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('symbol', models.CharField(max_length=12)),
                ('factor_to_base', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='1 of this unit = factor_to_base base units (e.g. 1 bag = 50 kg)', max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='accounting.unit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('TRADING', 'Trading Good'), ('RAW', 'Raw Material'), ('FINISHED', 'Finished Good')], default='TRADING', max_length=10)),
                ('rate_basis', models.CharField(choices=[('PER_KG', 'Per kg'), ('PER_UNIT', 'Per unit')], default='PER_KG', max_length=10)),
                ('business', models.CharField(choices=[('chicken_center', 'Sai Charan Chicken Center'), ('feeds', 'Sai Ram Feeds'), ('layer', 'Layer Farm'), ('common', 'Common / Shared')], default='chicken_center', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='accounting.account')),
                ('sales_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_items', to='accounting.account')),
                ('stock_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='accounting.account')),
                ('base_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='accounting.unit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('RECEIPT', 'Receipt'), ('PAYMENT', 'Payment'), ('EXPENSE', 'Expense'), ('PRODUCTION', 'Production'), ('SHRINKAGE', 'Shrinkage/Mortality'), ('JOURNAL', 'Journal'), ('OPENING', 'Opening Balance')], max_length=12)),
                ('narration', models.CharField(blank=True, max_length=300)),
                ('business', models.CharField(choices=[('chicken_center', 'Sai Charan Chicken Center'), ('feeds', 'Sai Ram Feeds'), ('layer', 'Layer Farm'), ('common', 'Common / Shared')], default='chicken_center', max_length=20)),
                ('source_module', models.CharField(blank=True, max_length=40)),
                ('source_ref', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by', to='accounting.voucher')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('PURCHASE_IN', 'Purchase In'), ('SALE_OUT', 'Sale Out'), ('PRODUCE_IN', 'Produced In'), ('CONSUME_OUT', 'Consumed In Production'), ('SHRINKAGE_OUT', 'Shrinkage/Mortality Out'), ('ADJUST', 'Adjustment')], max_length=16)),
                ('qty_in_base', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('qty_out_base', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('entered_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('business', models.CharField(choices=[('chicken_center', 'Sai Charan Chicken Center'), ('feeds', 'Sai Ram Feeds'), ('layer', 'Layer Farm'), ('common', 'Common / Shared')], default='chicken_center', max_length=20)),
                ('source_module', models.CharField(blank=True, max_length=40)),
                ('source_ref', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='accounting.item')),
                ('entered_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='accounting.unit')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='accounting.voucher')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.account')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.party')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounting.voucher')),
            ],
        ),
    ]
