# Generated by Django 6.1.1 on 2026-09-27 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(choices=[('chicken_center', 'Sai Charan Chicken Center'), ('feeds', 'Sai Ram Feeds'), ('layer', 'Layer Farm'), ('common', 'Common / Shared')], max_length=20, unique=True)),
                ('closed_through', models.DateField(blank=True, help_text='Books are locked on/before this date', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
