# Generated by Django 6.1.1 on 2026-10-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_booklock'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='party',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='party',
            name='pan',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='party',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_type',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('SUPPLIER', 'Supplier'), ('BOTH', 'Customer & Supplier')], default='BOTH', max_length=10),
        ),
    ]
