# Generated by Django 6.1.1 on 2026-09-26 18:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('TRADING', 'Trading Good'), ('RAW', 'Raw Material'), ('FINISHED', 'Finished Good')], default='TRADING', max_length=10)),
                ('rate_basis', models.CharField(choices=[('PER_KG', 'Per kg'), ('PER_UNIT', 'Per unit')], default='PER_KG', max_length=10)),
                ('business', models.CharField(choices=[('chicken_center', 'Sai Charan Chicken Center'), ('feeds', 'Sai Ram Feeds'), ('layer', 'Layer Farm'), ('common', 'Common / Shared')], default='chicken_center', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='accounting.account')),
                ('sales_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_items', to='accounting.account')),
                ('stock_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='accounting.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('symbol', models.CharField(max_length=12)),
                ('factor_to_base', models.DecimalField(decimal_places=4, default=Decimal('1'), help_text='1 of this unit = factor_to_base base units (e.g. 1 bag = 50 kg)', max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='inventory.unit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('PURCHASE_IN', 'Purchase In'), ('SALE_OUT', 'Sale Out'), ('PRODUCE_IN', 'Produced In'), ('CONSUME_OUT', 'Consumed In Production'), ('SHRINKAGE_OUT', 'Shrinkage/Mortality Out'), ('ADJUST', 'Adjustment')], max_length=16)),
                ('qty_in_base', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('qty_out_base', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('entered_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('business', models.CharField(choices=[('chicken_center', 'Sai Charan Chicken Center'), ('feeds', 'Sai Ram Feeds'), ('layer', 'Layer Farm'), ('common', 'Common / Shared')], default='chicken_center', max_length=20)),
                ('source_module', models.CharField(blank=True, max_length=40)),
                ('source_ref', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.item')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='accounting.voucher')),
                ('entered_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.unit')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='base_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.unit'),
        ),
    ]
