# Generated by Django 6.1.1 on 2026-10-02 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('business', models.CharField(choices=[('chicken_center', 'Sai Charan Chicken Center'), ('feeds', 'Sai Ram Feeds'), ('layer', 'Layer Farm'), ('common', 'Common / Shared')], default='layer', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('under', models.ForeignKey(blank=True, help_text="Parent group. Null only for the business's Primary group.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.stockgroup')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'business')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='stock_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.stockgroup'),
        ),
    ]
