# Generated by Django 6.1.1 on 2026-09-27 10:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Part of this receipt not applied to any bill (held as credit)', max_digits=14),
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTLY', 'Partly Paid'), ('PAID', 'Paid')], default='PENDING', max_length=8),
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='chicken_center.collection')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='chicken_center.sale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
