# Generated by Django 6.0.5 on 2026-06-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedrate_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedrate',
            options={'ordering': ['-week_start_date', 'feed_type']},
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='feed_consumed_kg',
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='feed_bfp_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='BFP (kg)'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='feed_bpsc_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='BPSC (kg)'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='feed_bsc_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='BSC (kg)'),
        ),
        migrations.AddField(
            model_name='feedrate',
            name='feed_type',
            field=models.CharField(choices=[('BPSC', 'BPSC (Pre-Starter Crumble)'), ('BSC', 'BSC (Starter Crumble)'), ('BFP', 'BFP (Finisher Pellet)')], default='BFP', max_length=10),
        ),
        migrations.AddField(
            model_name='flock',
            name='bpsc_per_bird_kg',
            field=models.DecimalField(decimal_places=3, default=0.5, help_text='kg of BPSC per bird', max_digits=6),
        ),
        migrations.AddField(
            model_name='flock',
            name='bsc_per_bird_kg',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='kg of BSC per bird', max_digits=6),
        ),
        migrations.AlterField(
            model_name='feedrate',
            name='rate_per_kg',
            field=models.DecimalField(decimal_places=2, help_text='Cost per kg in ₹', max_digits=10),
        ),
        migrations.AlterField(
            model_name='feedrate',
            name='week_start_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='feedrate',
            unique_together={('week_start_date', 'feed_type')},
        ),
    ]
