# Generated by Django 6.0.5 on 2026-06-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_feedrate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyentry',
            name='feed_bfp_kg',
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='feed_bpsc_kg',
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='feed_bsc_kg',
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='feed_bfp_bags',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='BFP (bags)'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='feed_bpsc_bags',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='BPSC (bags)'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='feed_bsc_bags',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='BSC (bags)'),
        ),
    ]
