# Generated by Django 6.0.5 on 2026-06-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_dailyentry_feed_bfp_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flock',
            name='breed',
        ),
        migrations.AlterField(
            model_name='flock',
            name='bpsc_per_bird_kg',
            field=models.DecimalField(decimal_places=3, default=0.5, help_text='Estimated BPSC per bird (kg)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='flock',
            name='bsc_per_bird_kg',
            field=models.DecimalField(decimal_places=3, default=1.0, help_text='Estimated BSC per bird (kg)', max_digits=6),
        ),
    ]
