# Generated by Django 6.0.5 on 2026-06-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_flock_breed_alter_flock_bpsc_per_bird_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_code',
            field=models.CharField(default='', help_text='Unique farm code given by user', max_length=50, unique=True),
        ),
    ]
