# Generated by Django 6.0.5 on 2026-06-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_farm_farm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='region',
            field=models.CharField(blank=True, help_text='Region/area for grouping farms', max_length=200),
        ),
    ]
