# Generated by Django 6.0.5 on 2026-06-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_farm_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='shed_type',
            field=models.CharField(choices=[('EC', 'EC (Environmentally Controlled)'), ('OPEN', 'Open Shed')], default='OPEN', max_length=10),
        ),
    ]
