# Generated by Django 6.0.5 on 2026-06-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_farm_shed_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='medication',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost in ₹', max_digits=10),
        ),
        migrations.AlterField(
            model_name='medication',
            name='route',
            field=models.CharField(blank=True, choices=[('water', 'Drinking Water'), ('feed', 'Feed'), ('injection', 'Injection'), ('spray', 'Spray'), ('eye_drop', 'Eye Drop'), ('other', 'Other')], max_length=20),
        ),
    ]
