# Generated by Django 6.0.5 on 2026-06-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_medication_options_medication_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='house_count',
        ),
        migrations.AddField(
            model_name='farm',
            name='capacity',
            field=models.PositiveIntegerField(default=5000, help_text='Farm bird capacity'),
        ),
    ]
