# Generated by Django 6.0.5 on 2026-06-02 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_farm_house_count_farm_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor')], default='supervisor', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('assigned_farms', models.ManyToManyField(blank=True, related_name='assigned_supervisors', to='core.farm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
