# Generated by Django 6.0.5 on 2026-06-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_feedorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='feed_bfp_bags',
            field=models.PositiveIntegerField(default=0, verbose_name='BFP (bags)'),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='feed_bpsc_bags',
            field=models.PositiveIntegerField(default=0, verbose_name='BPSC (bags)'),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='feed_bsc_bags',
            field=models.PositiveIntegerField(default=0, verbose_name='BSC (bags)'),
        ),
        migrations.AlterField(
            model_name='feedorder',
            name='quantity_bags',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('plant', 'Feed Plant')], default='supervisor', max_length=20),
        ),
    ]
