# Generated by Django 6.0.5 on 2026-06-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_dailyentry_feed_bfp_bags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_regions',
            field=models.JSONField(blank=True, default=list, help_text='List of region names assigned to this supervisor'),
        ),
    ]
