# Generated by Django 6.0.5 on 2026-06-08 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_assigned_regions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('BPSC', 'BPSC (Pre-Starter Crumble)'), ('BSC', 'BSC (Starter Crumble)'), ('BFP', 'BFP (Finisher Pellet)')], max_length=10)),
                ('quantity_bags', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_transfers_out', to='core.farm')),
                ('to_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_transfers_in', to='core.farm')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
