# Generated by Django 6.0.5 on 2026-06-09 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_feedtransfer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chick_cost_per_bird', models.DecimalField(decimal_places=2, default=34.0, max_digits=10)),
                ('feed_cost_per_kg', models.DecimalField(decimal_places=2, default=44.0, max_digits=10)),
                ('admin_cost_per_chick', models.DecimalField(decimal_places=2, default=6.0, max_digits=10)),
                ('standard_fcr', models.DecimalField(decimal_places=2, default=1.65, max_digits=5)),
                ('standard_mortality_pct', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('standard_production_cost', models.DecimalField(decimal_places=2, default=95.0, max_digits=10)),
                ('standard_growing_charges', models.DecimalField(decimal_places=2, default=6.5, max_digits=10)),
                ('min_growing_charges', models.DecimalField(decimal_places=2, default=4.5, max_digits=10)),
                ('incentive_threshold_1', models.DecimalField(decimal_places=2, default=110.0, max_digits=10)),
                ('incentive_threshold_2', models.DecimalField(decimal_places=2, default=120.0, max_digits=10)),
                ('incentive_rate_1', models.DecimalField(decimal_places=2, default=0.05, help_text='Per rupee per kg between threshold 1 and 2', max_digits=5)),
                ('incentive_rate_2', models.DecimalField(decimal_places=2, default=0.1, help_text='Per rupee per kg above threshold 2', max_digits=5)),
                ('max_rate_incentive', models.DecimalField(decimal_places=2, default=2.5, max_digits=10)),
                ('first_week_mortality_limit_pct', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('first_week_recovery_per_chick', models.DecimalField(decimal_places=2, default=34.0, max_digits=10)),
                ('negligence_rate_1_15', models.DecimalField(decimal_places=2, default=80.0, max_digits=10)),
                ('negligence_rate_16_20', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('negligence_rate_21_35', models.DecimalField(decimal_places=2, default=170.0, max_digits=10)),
                ('negligence_rate_above_35', models.DecimalField(decimal_places=2, default=190.0, max_digits=10)),
                ('ifft_per_bag', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('grade_a_plus_max', models.DecimalField(decimal_places=2, default=94.0, max_digits=10)),
                ('grade_a_max', models.DecimalField(decimal_places=2, default=95.0, max_digits=10)),
                ('grade_b_max', models.DecimalField(decimal_places=2, default=96.0, max_digits=10)),
                ('grade_c_max', models.DecimalField(decimal_places=2, default=97.0, max_digits=10)),
                ('grade_d_max', models.DecimalField(decimal_places=2, default=98.0, max_digits=10)),
                ('grade_incentive_pct', models.DecimalField(decimal_places=2, default=50.0, help_text='% increase for A+/A, decrease for B/C/D', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='recovery_excess_mortality',
            field=models.BooleanField(default=True, help_text='Apply 1st week excess mortality recovery'),
        ),
        migrations.AddField(
            model_name='farm',
            name='recovery_fcr',
            field=models.BooleanField(default=True, help_text='Apply FCR recovery if exceeds area avg'),
        ),
        migrations.AddField(
            model_name='farm',
            name='recovery_ifft',
            field=models.BooleanField(default=True, help_text='Apply IFFT charges per bag'),
        ),
        migrations.AddField(
            model_name='farm',
            name='recovery_negligence',
            field=models.BooleanField(default=False, help_text='Apply farmer negligence recovery'),
        ),
        migrations.AddField(
            model_name='farm',
            name='recovery_shortage',
            field=models.BooleanField(default=True, help_text='Apply bird shortage recovery'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('chicks_placed', models.PositiveIntegerField()),
                ('total_mortality', models.PositiveIntegerField()),
                ('live_birds', models.PositiveIntegerField()),
                ('total_sold_birds', models.PositiveIntegerField()),
                ('total_sold_weight_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age_days', models.PositiveIntegerField()),
                ('total_feed_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_feed_bags', models.DecimalField(decimal_places=2, max_digits=12)),
                ('chick_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('feed_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medicine_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('admin_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('production_cost_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('production_cost_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farmer_grade', models.CharField(max_length=5)),
                ('growing_charges_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('growing_charges_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_incentive_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate_incentive_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('first_week_mortality_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('negligence_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shortage_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fcr_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ifft_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_recoveries', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('config_snapshot', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('flock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='core.flock')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
