# Generated by Django 6.0.6 on 2026-06-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_billconfig_farm_recovery_excess_mortality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billconfig',
            name='medicine_cost_per_chick',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Default medicine cost per chick when not using actual', max_digits=10),
        ),
        migrations.AddField(
            model_name='farm',
            name='medicine_use_actual',
            field=models.BooleanField(default=False, help_text='If ON: use actual medicine cost. If OFF: use chicks × medicine_cost_per_chick'),
        ),
    ]
