# Generated by Django 6.0.7 on 2026-07-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_billconfig_medicine_cost_per_chick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='trader_name',
            field=models.CharField(blank=True, help_text='Trader/buyer name', max_length=200),
        ),
    ]
