# Generated by Django 6.0.7 on 2026-07-12 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sale_trader_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedorder',
            name='flock',
            field=models.ForeignKey(blank=True, help_text='Which flock this feed is for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_orders', to='core.flock'),
        ),
        migrations.AddField(
            model_name='feedtransfer',
            name='from_flock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_transfers_out', to='core.flock'),
        ),
        migrations.AddField(
            model_name='feedtransfer',
            name='to_flock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_transfers_in', to='core.flock'),
        ),
        migrations.AddField(
            model_name='flock',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_flocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
