# Generated by Django 6.1.1 on 2026-10-01 18:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_booklock'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('advance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank')], default='CASH', max_length=6)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('whatsapp_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layer_collections', to='accounting.party')),
                ('voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_collection', to='accounting.voucher')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EggSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trays', models.DecimalField(decimal_places=2, help_text='1 tray = 30 eggs', max_digits=12)),
                ('rate_per_tray', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_received', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTLY', 'Partly Paid'), ('PAID', 'Paid')], default='PENDING', max_length=8)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('whatsapp_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layer_egg_sales', to='accounting.party')),
                ('voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_eggsale', to='accounting.voucher')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='layer_farm.collection')),
                ('egg_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='layer_farm.eggsale')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('account_code', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank')], default='CASH', max_length=6)),
                ('split_across_flocks', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_expense', to='accounting.voucher')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeedBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('output_kg', models.DecimalField(decimal_places=3, max_digits=14)),
                ('materials_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cost_per_kg', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_batches', to='inventory.item')),
                ('voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_feedbatch', to='accounting.voucher')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeedBatchInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_kg', models.DecimalField(decimal_places=3, max_digits=14)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='layer_farm.feedbatch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='LayerFlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Batch-2026-A', max_length=80)),
                ('placement_date', models.DateField()),
                ('bird_count', models.PositiveIntegerField(help_text='Chicks/birds placed')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flocks', to='layer_farm.layerfarm')),
            ],
            options={
                'ordering': ['-placement_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FlockCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('CHICK', 'Chicks'), ('FEED', 'Feed'), ('MEDICINE', 'Medicine'), ('VACCINE', 'Vaccine'), ('PREMIX', 'Premix'), ('LABOUR', 'Labour'), ('OVERHEAD', 'Overhead'), ('OTHER', 'Other')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_costs', to='accounting.voucher')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='layer_farm.layerflock')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeedToFlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('qty_kg', models.DecimalField(decimal_places=3, max_digits=14)),
                ('cost_per_kg', models.DecimalField(decimal_places=4, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('feed_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_feedtoflock', to='accounting.voucher')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_transfers', to='layer_farm.layerflock')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='eggsale',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egg_sales', to='layer_farm.layerflock'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('MEDICINE', 'Medicine'), ('VACCINE', 'Vaccine'), ('PREMIX', 'Premix')], max_length=10)),
                ('date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_application', to='accounting.voucher')),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='layer_farm.layerflock')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK', 'Bank')], default='CASH', max_length=6)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layer_payments', to='accounting.party')),
                ('voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_payment', to='accounting.voucher')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RAW', 'Raw Material'), ('PREMIX', 'Premix'), ('MEDICINE', 'Medicine'), ('VACCINE', 'Vaccine'), ('CHICK', 'Chicks')], max_length=10)),
                ('date', models.DateField()),
                ('qty', models.DecimalField(decimal_places=3, help_text='kg for materials, birds for chicks', max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('flock', models.ForeignKey(blank=True, help_text='Set for CHICK purchases (charged to this flock)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='layer_farm.layerflock')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layer_purchases', to='inventory.item')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='layer_purchases', to='inventory.unit')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='layer_purchases', to='accounting.party')),
                ('voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='layer_purchase', to='accounting.voucher')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('eggs', models.PositiveIntegerField(default=0, help_text='Eggs laid (pieces)')),
                ('broken', models.PositiveIntegerField(default=0)),
                ('feed_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('mortality', models.PositiveIntegerField(default=0)),
                ('culls', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='layer_farm.layerflock')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('flock', 'date')},
            },
        ),
    ]
